[package]
name = "demotic"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1"
thiserror = "1.0"
anyhow = "1.0"
memmap = "0.7"
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4.0"
